#!/bin/sh

chmod +x /usr/bin/larksys

systemdthings=$(which systemctl||echo -n NONE)

if [ $systemdthings = 'NONE' ]; then
  echo "systemctl not found, systemd must not be in use, okay.";
  exit 0
else
  echo "enabling and restarting larksys systemd service";
  systemctl enable larksys && 
  systemctl restart larksys
fi
